name = "AnalyticMHDTestSolutions"
uuid = "fbea1840-634b-4ffc-8c6c-e633f751f78a"
authors = ["LudwigBoess <lboess@usm.lmu.de>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GadgetIO = "826b50da-1eb7-48f3-bd4b-d2350582c309"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Roots = "1.0"
GadgetIO = "0.3"
Interpolations = "0.13"
Distributions = "0.24"
ProgressMeter = "1.4"
SpecialFunctions = "1.0"
